/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package guessbattle;
import java.util.Random;
import javax.swing.JOptionPane;
import java.util.concurrent.TimeUnit;
import java.lang.*;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import project.Select;
/**
 *
 * @author rahat
 */
public class gamepage extends javax.swing.JFrame {
    
    /**
     * Creates new form gamepage
     */
    public gamepage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        p2show = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        p1number = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        p2number = new javax.swing.JTextField();
        guessnumber = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        p1enternumber = new javax.swing.JLabel();
        p2enternumber = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        win = new javax.swing.JLabel();
        p1show = new javax.swing.JLabel();
        health2 = new javax.swing.JLabel();
        player2health = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        health1 = new javax.swing.JLabel();
        pic1 = new javax.swing.JLabel();
        player1health = new javax.swing.JLabel();
        pic2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        BG = new javax.swing.JLabel();
        hidenp1 = new javax.swing.JTextField();
        hidenp2 = new javax.swing.JTextField();
        p1health = new javax.swing.JTextField();
        p2health = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Unispace", 3, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Battle");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(457, 33, 190, -1));

        jLabel2.setFont(new java.awt.Font("Source Code Pro Medium", 3, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("VS");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 500, -1, -1));

        p2show.setFont(new java.awt.Font("Unispace", 3, 24)); // NOI18N
        p2show.setForeground(new java.awt.Color(0, 0, 0));
        p2show.setText("()");
        getContentPane().add(p2show, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 220, 130, -1));

        jLabel4.setFont(new java.awt.Font("Unispace", 3, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Player 2");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 220, 130, -1));
        getContentPane().add(p1number, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 140, 180, 30));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("The Guess number is ");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 310, 180, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Guess Number player 2:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 170, 180, -1));
        getContentPane().add(p2number, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 170, 180, 30));

        guessnumber.setFont(new java.awt.Font("Unispace", 3, 36)); // NOI18N
        guessnumber.setForeground(new java.awt.Color(0, 0, 0));
        guessnumber.setText("1");
        getContentPane().add(guessnumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 330, 70, 80));

        jButton1.setText("Enter and Hide");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 140, -1, -1));

        jButton2.setText("Enter and Hide");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 170, -1, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Enter Numbers within 1 to 20");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 120, -1, -1));

        jButton3.setText("Guess");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 650, -1, 60));

        p1enternumber.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(p1enternumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 10, -1, -1));

        p2enternumber.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(p2enternumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 40, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Guess Number Player 1:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 140, 180, -1));

        win.setFont(new java.awt.Font("Unispace", 3, 24)); // NOI18N
        win.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(win, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 420, 210, 40));

        p1show.setFont(new java.awt.Font("Unispace", 3, 24)); // NOI18N
        p1show.setForeground(new java.awt.Color(0, 0, 0));
        p1show.setText("()");
        getContentPane().add(p1show, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 220, 130, -1));

        health2.setFont(new java.awt.Font("Unispace", 3, 24)); // NOI18N
        health2.setForeground(new java.awt.Color(0, 0, 0));
        health2.setText("Health:");
        getContentPane().add(health2, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 600, 130, -1));

        player2health.setFont(new java.awt.Font("Unispace", 3, 24)); // NOI18N
        player2health.setForeground(new java.awt.Color(0, 0, 0));
        player2health.setText("50");
        getContentPane().add(player2health, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 600, 130, -1));

        jLabel16.setFont(new java.awt.Font("Unispace", 3, 24)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 0, 0));
        jLabel16.setText("Player 1");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 220, 130, -1));

        health1.setFont(new java.awt.Font("Unispace", 3, 24)); // NOI18N
        health1.setForeground(new java.awt.Color(0, 0, 0));
        health1.setText("Health:");
        getContentPane().add(health1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 600, 130, -1));

        pic1.setText("jLabel3");
        getContentPane().add(pic1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 280, 280, 300));

        player1health.setFont(new java.awt.Font("Unispace", 3, 24)); // NOI18N
        player1health.setForeground(new java.awt.Color(0, 0, 0));
        player1health.setText("50");
        getContentPane().add(player1health, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 600, 130, -1));

        pic2.setText("jLabel3");
        getContentPane().add(pic2, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 270, 280, 300));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/back.png"))); // NOI18N
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel3MousePressed(evt);
            }
        });
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        BG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/Battle page.png"))); // NOI18N
        BG.setText("jLabel10");
        getContentPane().add(BG, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1110, -1));

        hidenp1.setText("jTextField1");
        getContentPane().add(hidenp1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 710, -1, -1));

        hidenp2.setText("jTextField2");
        getContentPane().add(hidenp2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 720, -1, -1));

        p1health.setText("50");
        getContentPane().add(p1health, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 720, -1, -1));

        p2health.setText("50");
        getContentPane().add(p2health, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 720, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        
        
        String s1=player1health.getText();
        String s2=player2health.getText();
        int hs1=Integer.parseInt(s1);
        int hs2=Integer.parseInt(s2);
        Random dice=new Random();
        int number;
        number=1+dice.nextInt(20);
        String num=String.valueOf(number);
        guessnumber.setText(num);
        String k1=hidenp1.getText();
        String k2=hidenp2.getText();
        int p1=Integer.parseInt(k1);
        int p2=Integer.parseInt(k2);
        
        int dfp1=Math.abs(p1-number);
        int dfp2=Math.abs(p2-number);
        
        System.out.println(dfp1);
        System.out.println(dfp2);
        
        if(dfp1<dfp2){
            win.setText("Player 1 wins");
            player2health.setText(String.valueOf(hs2-dfp2));
        }
        if(dfp1>dfp2){
            win.setText("Player 2 wins");
            player1health.setText(String.valueOf(hs1-dfp1));
        }
        if(dfp1==dfp2){
            JOptionPane.showMessageDialog(null, "Match Draw, Same Difference");
        }
        if(hs2-dfp2<0){
            JOptionPane.showMessageDialog(null, "Player 1 Wins the whole game");
            setVisible(false);
            new homepage().setVisible(true);
        }
        if(hs1-dfp1<0){
            JOptionPane.showMessageDialog(null, "Player 2 Wins the whole game");
            setVisible(false);
            new homepage().setVisible(true);
        }
        p1show.setText("("+k1+")");
        p2show.setText("("+k2+")");
        
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String p1=p1number.getText();
        int k=Integer.parseInt(p1);
        if(k>20 || k<0){
            JOptionPane.showMessageDialog(null, "Number out of bound, Enter valid Number");
        }
        else if(!p1.isEmpty()){
            p1enternumber.setText("Player 1 has Entered their guess");
        }
        p1number.setText("");
        hidenp1.setText(p1);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String p1=p2number.getText();
        int k=Integer.parseInt(p1);
        if(k>21 || k<0){
            JOptionPane.showMessageDialog(null, "Number out of bound, Enter valid Number");
        }
        else if(!p1.isEmpty()){
            p2enternumber.setText("Player 2 has Entered their guess");
        }
        p2number.setText("");
        hidenp2.setText(p1);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        String player1 = null;
        ResultSet rs=Select.getData("SELECT * FROM `player_`");
        try {
            while(rs.next()){
                player1=rs.getString("player1");
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
        player1+=".gif";
        ImageIcon pc1=new ImageIcon(player1);
        pic1.setIcon(pc1);
        
        String player2 = null;
        ResultSet rs1=Select.getData("SELECT * FROM `player_`");
        try {
            while(rs1.next()){
                player2=rs1.getString("player2");
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
        player2+=".gif";
        ImageIcon pc2=new ImageIcon(player2);
        pic2.setIcon(pc2);
    }//GEN-LAST:event_formComponentShown

    private void jLabel3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MousePressed
        // TODO add your handling code here:
        setVisible(false);
        new Selection_page().setVisible(true);
    }//GEN-LAST:event_jLabel3MousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(gamepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(gamepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(gamepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(gamepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new gamepage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BG;
    private javax.swing.JLabel guessnumber;
    private javax.swing.JLabel health1;
    private javax.swing.JLabel health2;
    public javax.swing.JTextField hidenp1;
    public javax.swing.JTextField hidenp2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel p1enternumber;
    private javax.swing.JTextField p1health;
    private javax.swing.JTextField p1number;
    private javax.swing.JLabel p1show;
    private javax.swing.JLabel p2enternumber;
    private javax.swing.JTextField p2health;
    private javax.swing.JTextField p2number;
    private javax.swing.JLabel p2show;
    private javax.swing.JLabel pic1;
    private javax.swing.JLabel pic2;
    private javax.swing.JLabel player1health;
    private javax.swing.JLabel player2health;
    private javax.swing.JLabel win;
    // End of variables declaration//GEN-END:variables
}
